name: Get secrets
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run script
        env:
          MY_VAR: 'this is my var'
          DEPLOYMENT_APPS: ${{secrets.HEROKU_APP_LIST}}
        # run: echo "$MY_VAR"
        run: echo my secrets ${{secrets.HEROKU_APP_LIST}} "$MY_VAR" | sed 's/./& /g'
        # env:
        # DEPLOYMENT_APPS: ${{secrets.HEROKU_APP_LIST}}
        # run: npm run deploy development "$DEPLOYMENT_APPS"
